# Generated by Django 5.2 on 2026-03-26 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrolment_close',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='enrolment_open',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='enrolment_type',
            field=models.CharField(choices=[('open', 'Open — anyone can enrol'), ('approval', 'Requires teacher approval'), ('invite', 'Invite only')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='prerequisite',
            field=models.ForeignKey(blank=True, help_text='Student must complete this lesson first', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='lessoncompletion',
            name='time_spent_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LessonFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lesson_files/')),
                ('label', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCompletionCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('certificate_number', models.CharField(max_length=40, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
