# Generated by Django 5.2 on 2026-04-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_enrolment_close_course_enrolment_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='release_at',
            field=models.DateTimeField(blank=True, help_text='Optional scheduled release time for students.', null=True),
        ),
    ]
