# Generated by Django 5.2 on 2026-03-26 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notif_type', models.CharField(choices=[('enrolment', 'Enrolment confirmed'), ('enrolment_request', 'Enrolment request'), ('enrolment_approved', 'Enrolment approved'), ('enrolment_rejected', 'Enrolment rejected'), ('assignment_graded', 'Assignment graded'), ('announcement', 'Announcement'), ('certificate', 'Certificate issued'), ('general', 'General')], default='general', max_length=30)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
